//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Building_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBJECT()
        {
            this.used_materials = new HashSet<used_materials>();
            this.WorkSheldues = new HashSet<WorkSheldue>();
        }
    
        public int idObject { get; set; }
        public Nullable<System.DateTime> orderData { get; set; }
        public string status { get; set; }
        public string comments { get; set; }
        public string country { get; set; }
        public string addressLine { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> income { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<used_materials> used_materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSheldue> WorkSheldues { get; set; }
    }
}
