//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Building_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class used_materials
    {
        public int used_Material_Id { get; set; }
        public Nullable<int> idObject { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<decimal> uniPrice { get; set; }
        public Nullable<int> idUnit { get; set; }
        public Nullable<int> supplierID { get; set; }
        public Nullable<int> idMatterial { get; set; }
    
        public virtual MATERIAL MATERIAL { get; set; }
        public virtual OBJECT OBJECT { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
