//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Building_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSheldue
    {
        public int idWorkShedule { get; set; }
        public Nullable<int> idObject { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> startWork { get; set; }
        public Nullable<System.DateTime> finishWork { get; set; }
        public string description { get; set; }
        public Nullable<int> idUnit { get; set; }
        public Nullable<int> workTypeId { get; set; }
    
        public virtual OBJECT OBJECT { get; set; }
        public virtual UNIT UNIT { get; set; }
        public virtual WorkType WorkType { get; set; }
    }
}
